\c herbology_dev;

INSERT INTO biosystems (name, description, functionality, primaryOrgans, associatedDiseases, chakra, element, has_regenerative_capacity, averageRecoveryTime) VALUES
1('Musculoskeletal System', 'The system providing structural support, movement, and protection for the body.', 'Supports body structure, enables movement, and protects vital organs.', 'Bones, Muscles, Joints', 'Osteoporosis, Arthritis, Muscular Dystrophy', 'Root', 'Earth', true, 30),
2('Hematologic System', 'The system involved in the production and function of blood cells and the blood-forming organs.', 'Responsible for blood production, immune response, and oxygen transport.', 'Bone Marrow, Blood, Spleen', 'Anemia, Leukemia, Hemophilia', 'Root', 'Fire', true, 7), 
3('Integumentary System', 'The system that includes the skin and its associated structures.', 'Protects the body from external damage and regulates temperature.', 'Skin, Hair, Nails', 'Eczema, Psoriasis, Acne', 'Root', 'Earth', true, 14),
4('Tactile System', 'The system responsible for processing touch and pressure sensations.', 'Receives and interprets sensations of touch, pressure, and temperature.', 'Skin, Nerve Endings', 'Sensory Neuropathy, Hyperesthesia', 'Root', 'Earth', true, 7),
5('Gustatory System', 'The system responsible for processing taste sensations.', 'Receives and interprets flavors from ingested substances.', 'Tongue, Taste Buds', 'Loss of Taste, Taste Disorders', 'Sacral', 'Water', true, 7),
6('Urinary System', 'The system responsible for eliminating waste and regulating fluid and electrolyte balance.', 'Filters blood to produce urine and regulates fluid and electrolyte balance.', 'Kidneys, Ureters, Bladder, Urethra', 'Urinary Tract Infections, Kidney Stones, Incontinence', 'Sacral', 'Water', true, 21),
7('Reproductive System', 'The system involved in producing offspring and regulating sexual functions.', 'Facilitates reproduction and regulates sexual health.', 'Ovaries, Uterus, Testes, Prostate', 'Infertility, Polycystic Ovary Syndrome, Erectile Dysfunction', 'Sacral', 'Water', true, 30),
8('Excretory System', 'The system responsible for removing waste products and excess substances from the blood.', 'Filters and eliminates waste through various mechanisms.', 'Kidneys, Bladder, Urethra, Skin', 'Kidney Stones, Urinary Tract Infections, Sweat Disorders', 'Sacral', 'Water', true, 14),
9('Digestive System', 'A complex system responsible for breaking down food, absorbing nutrients, and expelling waste.', 'Breaks down food into nutrients, absorbs nutrients, and removes waste.', 'Stomach, Intestines, Liver, Pancreas, Gallbladder', 'Gastritis, Peptic Ulcers, Irritable Bowel Syndrome, Crohns Disease', 'Solar Plexus', 'Fire', true, 7),
10('Cardiovascular System', 'The system that circulates blood throughout the body, delivering oxygen and nutrients while removing waste.', 'Pumps blood throughout the body, delivering oxygen and nutrients to tissues and removing waste products.', 'Heart, Blood Vessels, Blood', 'Hypertension, Heart Disease, Atherosclerosis', 'Heart', 'Water', true, 10),
11('Respiratory System', 'The system responsible for the exchange of oxygen and carbon dioxide between the body and the environment.', 'Facilitates breathing by exchanging gases between the blood and the air.', 'Lungs, Trachea, Bronchi, Diaphragm', 'Asthma, Chronic Obstructive Pulmonary Disease (COPD), Pneumonia', 'Heart', 'Air', false, 14),
12('Lymphatic System', 'A network of tissues and organs that help rid the body of toxins and waste.', 'Transports lymph, a fluid containing infection-fighting white blood cells.', 'Lymph Nodes, Lymph Vessels, Spleen, Thymus', 'Lymphedema, Lymphoma, Tonsillitis', 'Heart', 'Water', true, 20),
13('Immune System', 'The system that defends the body against infections and disease.', 'Identifies and destroys pathogens, and removes damaged cells.', 'Lymph Nodes, Spleen, Bone Marrow, Antibodies', 'Autoimmune Diseases, Allergies, Immunodeficiency Disorders', 'Throat', 'Ether', true, 14),
14('Oral System', 'The system responsible for the intake of food, initial digestion, and vocal communication.', 'Enables ingestion of food, initial digestion, and speech.', 'Mouth, Teeth, Tongue, Salivary Glands', 'Oral Cancer, Gingivitis, Dental Caries', 'Throat', 'Water', true, 7),
15('Auditory System', 'The system responsible for processing sound and maintaining balance.', 'Receives and processes sound waves and maintains equilibrium.', 'Ears, Cochlea, Auditory Nerve', 'Hearing Loss, Tinnitus, Menieres Disease', 'Third Eye', 'Ether', true, 10),
16('Ocular System', 'The system responsible for vision and processing visual information.', 'Enables vision by processing light and transmitting visual signals to the brain.', 'Eyes, Retina, Optic Nerve', 'Cataracts, Glaucoma, Macular Degeneration', 'Third Eye', 'Ether', true, 15),
17('Olfactory System', 'The system responsible for processing smell and detecting odors.', 'Receives and processes odor molecules to create the sense of smell.', 'Nose, Olfactory Bulb', 'Anosmia, Hyposmia', 'Third Eye', 'Ether', true, 7),
18('Endocrine System', 'A collection of glands that produce hormones regulating metabolism, growth, and other functions.', 'Regulates various physiological processes through hormone secretion.', 'Pituitary Gland, Thyroid Gland, Adrenal Glands', 'Diabetes Mellitus, Hypothyroidism, Addisons Disease', 'Third Eye', 'Air', true, 21),
19('Cellular Organelle Systems', 'The systems within cells that carry out specific functions essential for cell survival.', 'Includes mitochondria, nuclei, ribosomes, and endoplasmic reticulum.', 'Mitochondria, Nucleus, Ribosomes, Endoplasmic Reticulum', 'Mitochondrial Diseases, Nucleus Disorders, Ribosomal Protein Deficiencies', 'Crown', 'Ether', true, 5),
20('Nervous System', 'The system that transmits nerve impulses between parts of the body and the brain.', 'Controls and coordinates body activities by transmitting electrical signals.', 'Brain, Spinal Cord, Nerves', 'Alzheimers Disease, Parkinsons Disease, Multiple Sclerosis', 'Crown', 'Ether', false, 30);

INSERT INTO herbs (name, imageURL, partsUsed, family, genus, nutrients, activeCompounds, medicinalUses, precautions, potencyRating, chakra, element, biosystem, addtlsystem, biosystem_id) VALUES
('Abuta', 'https://example.com/abuta.jpg', 'Stem', 'Menispermaceae', 'Abuta', 'Alkaloids, Flavonoids', 'Isoquinoline alkaloids, Flavonoids', 'Pain relief, Anti-inflammatory', 'May cause dizziness', 6, 'Root', 'Earth', 'Musculoskeletal', 'Immune', 1),
('Acai', 'https://example.com/acai.jpg', 'Fruit', 'Arecaceae', 'Euterpe', 'Anthocyanins, Vitamin C', 'Acai anthocyanins, Flavonoids', 'Antioxidant, Heart health', 'May cause digestive upset', 6, 'Root', 'Earth', 'Cardiovascular', 'Immune', 10),
('Aloe Vera', 'https://example.com/aloe_vera.jpg', 'Leaves', 'Asphodelaceae', 'Aloe', 'Aloin, Polysaccharides', 'Aloin, Polysaccharides', 'Skin health, Digestive aid', 'May cause skin irritation', 6, 'Heart', 'Water', 'Integumentary', 'Digestive', 3),
('Andiroba', 'https://example.com/andiroba.jpg', 'Oil', 'Meliaceae', 'Carapa', 'Limonene, Triterpenes', 'Limonene, Triterpenes', 'Anti-inflammatory, Skin health', 'May cause skin irritation', 6, 'Root', 'Earth', 'Integumentary', 'Immune', 3),
('Arnica', 'https://example.com/arnica.jpg', 'Flowers', 'Asteraceae', 'Arnica', 'Sesquiterpene lactones, Flavonoids', 'Helenalin, Flavonoids', 'Anti-inflammatory, Pain relief', 'May cause skin irritation', 7, 'Solar Plexus', 'Fire', 'Musculoskeletal', 'Integumentary', 1),
('Artichoke', 'https://example.com/artichoke.jpg', 'Leaves', 'Asteraceae', 'Cynara', 'Inulin, Cynarin', 'Cynarin, Silymarin', 'Digestive aid, Liver support', 'May cause allergic reactions', 7, 'Heart', 'Earth', 'Digestive', 'Urinary', 9),
('Ashwagandha', 'https://example.com/ashwagandha.jpg', 'Root', 'Solanaceae', 'Withania', 'Withanolides, Iron', 'Withanolides, Alkaloids', 'Stress relief, Immune support', 'May cause digestive upset', 7, 'Root', 'Earth', 'Nervous', 'Immune', 20),
('Asian Ginseng', 'https://example.com/asian_ginseng.jpg', 'Root', 'Araliaceae', 'Panax', 'Ginsenosides, Polysaccharides', 'Ginsenosides, Polysaccharides', 'Energy boost, Immune support', 'May cause insomnia', 8, 'Root', 'Earth', 'Immune', 'Nervous', 13),
('Astragalus', 'https://example.com/astragalus.jpg', 'Root', 'Fabaceae', 'Astragalus', 'Polysaccharides, Saponins', 'Astragalosides, Isoflavonoids', 'Immune support, Anti-inflammatory', 'May interact with immunosuppressive medications', 7, 'Heart', 'Earth', 'Immune', 'Cardiovascular', 13),
('Bitter Melon', 'https://example.com/bitter_melon.jpg', 'Fruit', 'Cucurbitaceae', 'Momordica', 'Charantin, Vitamin C', 'Momordicin, Charantin', 'Blood sugar regulation, Antioxidant', 'May cause digestive upset', 6, 'Heart', 'Water', 'Endocrine', 'Immune', 18),
('Chuchuhuasi', 'https://example.com/chuchuhuasi.jpg', 'Bark', 'Malvaceae', 'Maytenus', 'Alkaloids, Triterpenes', 'Maytenin, Pristimerin', 'Anti-inflammatory, Pain relief', 'May cause dizziness', 6, 'Root', 'Earth', 'Musculoskeletal', 'Immune', 1),
('Copaiba', 'https://example.com/copaiba.jpg', 'Resin', 'Fabaceae', 'Copaifera', 'Caryophyllene, Terpenoids', 'Caryophyllene, Terpenoids', 'Anti-inflammatory, Pain relief', 'May cause digestive upset', 6, 'Root', 'Earth', 'Musculoskeletal', 'Immune', 1),
('Bilberry', 'https://example.com/bilberry.jpg', 'Fruit', 'Ericaceae', 'Vaccinium', 'Anthocyanins, Vitamin C', 'Anthocyanins, Flavonoids', 'Antioxidant, Eye health', 'May cause digestive upset', 5, 'Third Eye', 'Air', 'Ocular', 'Immune', 16),
('Bitter Orange', 'https://example.com/bitter_orange.jpg', 'Fruit', 'Rutaceae', 'Citrus', 'Synephrine, Flavonoids', 'Synephrine, Flavonoids', 'Appetite suppressant, Energy boost', 'May cause increased heart rate', 5, 'Solar Plexus', 'Fire', 'Digestive', 'Cardiovascular', 9),
('Black Cohosh', 'https://example.com/black_cohosh.jpg', 'Root', 'Ranunculaceae', 'Actaea', 'Triterpene glycosides, Isoflavones', 'Actein, Isoflavones', 'Hormonal balance, Menopausal support', 'May cause digestive upset', 6, 'Sacral', 'Water', 'Reproductive', 'Endocrine', 7),
('Bromelain', 'https://example.com/bromelain.jpg', 'Stem', 'Bromeliaceae', 'Ananas', 'Proteolytic enzymes, Vitamin C', 'Bromelain, Flavonoids', 'Anti-inflammatory, Digestive aid', 'May cause digestive upset', 7, 'Solar Plexus', 'Fire', 'Digestive', 'Musculoskeletal', 9),
('Butterbur', 'https://example.com/butterbur.jpg', 'Root', 'Asteraceae', 'Petasites', 'Petasin, Flavonoids', 'Petasin, Flavonoids', 'Allergy relief, Migraine prevention', 'May cause liver damage', 5, 'Crown', 'Air', 'Nervous', 'Immune', 20),
('Carqueja', 'https://example.com/carqueja.jpg', 'Aerial parts', 'Asteraceae', 'Baccharis', 'Flavonoids, Saponins', 'Baccharin, Baccharis oxide', 'Digestive aid, Liver support', 'May cause digestive upset', 6, 'Solar Plexus', 'Fire', 'Digestive', 'Urinary', 9),
('Cats Claw', 'https://example.com/cats_claw.jpg', 'Bark', 'Rubiaceae', 'Uncaria', 'Oxindole alkaloids, Flavonoids', 'Rhynchophylline, Flavonoids', 'Anti-inflammatory, Immune support', 'May cause digestive upset', 6, 'Root', 'Earth', 'Immune', 'Musculoskeletal', 13),
('Chamomile', 'https://example.com/chamomile.jpg', 'Flowers', 'Asteraceae', 'Matricaria', 'Apigenin, Flavonoids', 'Apigenin, Chamazulene', 'Sleep aid, Digestive aid', 'May cause allergic reactions', 6, 'Solar Plexus', 'Water', 'Digestive', 'Nervous', 9),
('Chasteberry', 'https://example.com/chasteberry.jpg', 'Fruit', 'Lamiaceae', 'Vitex', 'Agnuside, Flavonoids', 'Agnuside, Flavonoids', 'Hormonal balance, Menstrual support', 'May cause digestive upset', 6, 'Sacral', 'Water', 'Reproductive', 'Endocrine', 7),
('Cinnamon', 'https://example.com/cinnamon.jpg', 'Bark', 'Lauraceae', 'Cinnamomum', 'Cinnamaldehyde, Flavonoids', 'Cinnamaldehyde, Eugenol', 'Blood sugar regulation, Antioxidant', 'May cause digestive upset', 7, 'Sacral', 'Fire', 'Cardiovascular', 'Digestive', 9),
('Clavillia', 'https://example.com/clavillia.jpg', 'Leaves', 'Nyctaginaceae', 'Mirabilis', 'Flavonoids, Alkaloids', 'Mirabilin, Mirabilis antiviral protein', 'Anti-inflammatory, Immune support', 'May cause digestive upset', 5, 'Solar Plexus', 'Fire', 'Immune', 'Musculoskeletal', 13),
('Cranberry', 'https://example.com/cranberry.jpg', 'Fruit', 'Ericaceae', 'Vaccinium', 'Proanthocyanidins, Vitamin C', 'Proanthocyanidins, Flavonoids', 'Urinary health, Antioxidant', 'May cause digestive upset', 6, 'Sacral', 'Water', 'Urinary', 'Immune', 6),
('Damiana', 'https://example.com/damiana.jpg', 'Leaves', 'Passifloraceae', 'Turnera', 'Apigenin, Flavonoids', 'Damiana flavonoid, Apigenin', 'Aphrodisiac, Mood enhancement', 'May cause digestive upset', 5, 'Sacral', 'Water', 'Reproductive', 'Nervous', 7),
('Dandelion', 'https://example.com/dandelion.jpg', 'Root', 'Asteraceae', 'Taraxacum', 'Inulin, Flavonoids', 'Taraxacin, Flavonoids', 'Digestive aid, Liver support', 'May cause allergic reactions', 5, 'Solar Plexus', 'Fire', 'Digestive', 'Urinary', 9),
('Echinacea', 'https://example.com/echinacea.jpg', 'Root', 'Asteraceae', 'Echinacea', 'Alkamides, Polysaccharides', 'Echinacoside, Flavonoids', 'Immune support, Anti-inflammatory', 'May cause allergic reactions', 7, 'Root', 'Earth', 'Immune', 'Respiratory', 13),
('Elderberry', 'https://example.com/elderberry.jpg', 'Fruit', 'Adoxaceae', 'Sambucus', 'Anthocyanins, Vitamin C', 'Anthocyanins, Flavonoids', 'Immune support, Antioxidant', 'May cause digestive upset', 6, 'Throat', 'Water', 'Immune', 'Respiratory', 13),
('Epazote', 'https://example.com/epazote.jpg', 'Leaves', 'Amaranthaceae', 'Dysphania', 'Ascaridole, Flavonoids', 'Ascaridole, Isoascaridole', 'Digestive aid, Anti-parasitic', 'May cause digestive upset', 6, 'Solar Plexus', 'Fire', 'Digestive', 'Immune', 9),
('Ephedra', 'https://example.com/ephedra.jpg', 'Stem', 'Ephedraceae', 'Ephedra', 'Ephedrine, Flavonoids', 'Ephedrine, Pseudoephedrine', 'Energy boost, Weight loss', 'May cause increased heart rate', 7, 'Solar Plexus', 'Fire', 'Respiratory', 'Cardiovascular', 11),
('Erva Tostao', 'https://example.com/erva_tostao.jpg', 'Root', 'Rubiaceae', 'Borreria', 'Alkaloids, Flavonoids', 'Borreriine, Borrerine', 'Diuretic, Anti-inflammatory', 'May cause digestive upset', 6, 'Root', 'Earth', 'Urinary', 'Musculoskeletal', 6),
('European Mistletoe', 'https://example.com/european_mistletoe.jpg', 'Leaves', 'Santalaceae', 'Viscum', 'Viscotoxins, Lectins', 'Viscotoxins, Lectins', 'Immune support, Anti-cancer', 'May cause digestive upset', 5, 'Heart', 'Earth', 'Cardiovascular',  'Immune', 10),
('Evening Primrose Oil', 'https://example.com/evening_primrose_oil.jpg', 'Seeds', 'Onagraceae', 'Oenothera', 'Gamma-linolenic acid, Flavonoids', 'Gamma-linolenic acid, Flavonoids', 'Hormonal balance, Skin health', 'May cause digestive upset', 6, 'Sacral', 'Water', 'Reproductive', 'Integumentary', 7),
('Fedegoso', 'https://example.com/fedegoso.jpg', 'Leaves', 'Fabaceae', 'Cassia', 'Flavonoids, Saponins', 'Emodin, Rhein', 'Digestive aid, Laxative', 'May cause digestive upset', 5, 'Solar Plexus', 'Fire', 'Digestive', 'Immune', 9),
('Fenugreek', 'https://example.com/fenugreek.jpg', 'Seeds', 'Fabaceae', 'Trigonella', 'Saponins, Flavonoids', 'Fenugreek saponins, Flavonoids', 'Digestive aid, Blood sugar regulation', 'May cause digestive upset', 5, 'Solar Plexus', 'Fire', 'Endocrine', 'Digestive', 18),
('Feverfew', 'https://example.com/feverfew.jpg', 'Leaves', 'Asteraceae', 'Tanacetum', 'Parthenolide, Flavonoids', 'Parthenolide, Flavonoids', 'Migraine prevention, Anti-inflammatory', 'May cause digestive upset', 6, 'Crown', 'Air', 'Nervous', 'Musculoskeletal', 20),
('Flaxseed', 'https://example.com/flaxseed.jpg', 'Seeds', 'Linaceae', 'Linum', 'Alpha-linolenic acid, Lignans', 'Alpha-linolenic acid, Lignans', 'Heart health, Digestive aid', 'May cause digestive upset', 6, 'Throat', 'Water', 'Cardiovascular', 'Digestive', 10),
('Garcinia Cambogia', 'https://example.com/garcinia_cambogia.jpg', 'Fruit', 'Clusiaceae', 'Garcinia', 'Hydroxycitric acid, Flavonoids', 'Hydroxycitric acid, Flavonoids', 'Weight loss, Appetite suppressant', 'May cause digestive upset', 5, 'Solar Plexus', 'Fire', 'Digestive', 'Endocrine', 9),
('Garlic', 'https://example.com/garlic.jpg', 'Bulb', 'Amaryllidaceae', 'Allium', 'Allicin, Flavonoids', 'Allicin, S-allyl cysteine', 'Heart health, Immune support', 'May cause digestive upset', 8, 'Heart', 'Earth', 'Cardiovascular', 'Immune', 10),
('Ginger', 'https://example.com/ginger.jpg', 'Rhizome', 'Zingiberaceae', 'Zingiber', 'Gingerol, Vitamin B6, Potassium', 'Gingerol, Shogaol, Zingerone', 'Anti-nausea, Anti-inflammatory, Pain relief', 'May cause digestive upset in large amounts', 7, 'Solar Plexus', 'Fire', 'Digestive', 'Immune', 9),
('Ginkgo Biloba', 'https://example.com/ginkgo.jpg', 'Leaves', 'Ginkgoaceae', 'Ginkgo', 'Flavonoids, Terpenoids', 'Ginkgolides, Bilobalide', 'Cognitive support, Circulatory health', 'May cause digestive upset', 7, 'Crown', 'Air', 'Nervous', 'Cardiovascular', 20),
('Goldenseal', 'https://example.com/goldenseal.jpg', 'Root', 'Ranunculaceae', 'Hydrastis', 'Berberine, Hydrastine', 'Berberine, Hydrastine', 'Antimicrobial, Immune support', 'May cause digestive upset', 6, 'Solar Plexus', 'Fire', 'Digestive', 'Immune', 9),
('Grape Seed Extract', 'https://example.com/grape_seed_extract.jpg', 'Seeds', 'Vitaceae', 'Vitis', 'Proanthocyanidins, Flavonoids', 'Proanthocyanidins, Flavonoids', 'Antioxidant, Circulatory health', 'May cause digestive upset', 6, 'Heart', 'Earth', 'Cardiovascular', 'Immune', 10),
('Green Tea', 'https://example.com/green_tea.jpg', 'Leaves', 'Theaceae', 'Camellia', 'Catechins, Flavonoids', 'Epigallocatechin gallate, Flavonoids', 'Antioxidant, Weight loss', 'May cause digestive upset', 7, 'Heart', 'Earth', 'Cardiovascular', 'Digestive', 10),
('Hawthorn', 'https://example.com/hawthorn.jpg', 'Fruit', 'Rosaceae', 'Crataegus', 'Flavonoids, Procyanidins', 'Flavonoids, Procyanidins', 'Heart health, Circulatory health', 'May cause digestive upset', 7, 'Heart', 'Earth', 'Cardiovascular', 'Immune', 10),
('Hoodia', 'https://example.com/hoodia.jpg', 'Stem', 'Apocynaceae', 'Hoodia', 'P57, Flavonoids', 'P57, Flavonoids', 'Appetite suppressant, Weight loss', 'May cause digestive upset', 6, 'Solar Plexus', 'Fire', 'Endocrine', 'Digestive', 18),
('Horse Chestnut', 'https://example.com/horse_chestnut.jpg', 'Seeds', 'Sapindaceae', 'Aesculus', 'Aescin, Flavonoids', 'Aescin, Flavonoids', 'Circulatory health, Anti-inflammatory', 'May cause digestive upset', 6, 'Root', 'Earth', 'Cardiovascular', 'Immune', 10),
('Juazeiro', 'https://example.com/juazeiro.jpg', 'Bark', 'Rhamnaceae', 'Ziziphus', 'Saponins, Flavonoids', 'Juazeiro saponin, Flavonoids', 'Oral health, Anti-inflammatory', 'May cause digestive upset', 6, 'Root', 'Earth', 'Oral', 'Immune', 14),
('Jurubeba', 'https://example.com/jurubeba.jpg', 'Leaves', 'Solanaceae', 'Solanum', 'Alkaloids, Flavonoids', 'Solasonine, Solamargine', 'Digestive aid, Liver support', 'May cause digestive upset', 5, 'Solar Plexus', 'Fire', 'Digestive', 'Immune', 9),
('Kalanchoe', 'https://example.com/kalanchoe.jpg', 'Leaves', 'Crassulaceae', 'Kalanchoe', 'Flavonoids, Triterpenoids', 'Bryophyllin, Quercetin', 'Wound healing, Anti-inflammatory', 'May cause skin irritation', 5, 'Heart', 'Water', 'Integumentary', 'Immune', 3),
('Kava', 'https://example.com/kava.jpg', 'Root', 'Piperaceae', 'Piper', 'Kavalactones, Flavonoids', 'Kavalactones, Flavonoids', 'Anxiety relief, Sleep aid', 'May cause liver damage', 7, 'Solar Plexus', 'Water', 'Nervous', 'Immune', 20),
('Lavender', 'https://example.com/lavender.jpg', 'Flowers', 'Lamiaceae', 'Lavandula', 'Linalool, Linalyl acetate, Vitamin A', 'Linalool, Linalyl acetate, Cineole', 'Anxiety relief, Sleep aid, Antiseptic', 'May cause skin irritation in sensitive individuals', 5, 'Third Eye', 'Air', 'Nervous', 'Integumentary', 20),
('Licorice Root', 'https://example.com/licorice_root.jpg', 'Root', 'Fabaceae', 'Glycyrrhiza', 'Glycyrrhizin, Flavonoids', 'Glycyrrhizin, Flavonoids', 'Digestive aid, Anti-inflammatory', 'May cause high blood pressure', 6, 'Solar Plexus', 'Fire', 'Digestive', 'Immune', 9),
('Milk Thistle', 'https://example.com/milk_thistle.jpg', 'Seeds', 'Asteraceae', 'Silybum', 'Silymarin, Flavonoids', 'Silymarin, Flavonoids', 'Liver support, Antioxidant', 'May cause digestive upset', 7, 'Solar Plexus', 'Fire', 'Digestive', 'Endocrine', 9),
('Mugwort', 'https://example.com/mugwort.jpg', 'Leaves', 'Asteraceae', 'Artemisia', 'Thujone, Flavonoids', 'Thujone, Flavonoids', 'Digestive aid, Menstrual support', 'May cause allergic reactions', 6, 'Solar Plexus', 'Fire', 'Digestive', 'Endocrine', 9),
('Mullein', 'https://example.com/mullein.jpg', 'Leaves, Flowers', 'Scrophulariaceae', 'Verbascum', 'Vitamins A, C, and E, Saponins, Flavonoids', 'Saponins, Glycosides, Flavonoids', 'Respiratory support, cough relief, soothing mucous membranes', 'May cause allergic reactions', 7, 'Throat', 'Air', 'Respiratory', 'Immune', 11),
('Mutamba', 'https://example.com/mutamba.jpg', 'Bark', 'Malvaceae', 'Guazuma', 'Tannins, Flavonoids', 'Guazuma tannin, Flavonoids', 'Anti-inflammatory, Pain relief', 'May cause digestive upset', 5, 'Root', 'Earth', 'Musculoskeletal', 'Immune', 1),
('Noni', 'https://example.com/noni.jpg', 'Fruit', 'Rubiaceae', 'Morinda', 'Iridoids, Flavonoids', 'Scopolein, Damnacanthal', 'Immune support, Antioxidant', 'May cause digestive upset', 6, 'Solar Plexus', 'Fire', 'Immune', 'Digestive', 13),
('Passionflower', 'https://example.com/passionflower.jpg', 'Leaves', 'Passifloraceae', 'Passiflora', 'Flavonoids, Alkaloids', 'Passiflorine, Harmine', 'Anxiety relief, Sleep aid', 'May cause digestive upset', 6, 'Heart', 'Water', 'Nervous', 'Immune', 20),
('Pau d Arco', 'https://example.com/pau_darco.jpg', 'Bark', 'Bignoniaceae', 'Tabebuia', 'Lapachol, Quercetin', 'Lapachol, Quercetin', 'Antimicrobial, Immune support', 'May cause digestive upset', 6, 'Heart', 'Earth', 'Immune', 'Musculoskeletal', 13),
('Peppermint', 'https://example.com/peppermint.jpg', 'Leaves', 'Lamiaceae', 'Mentha', 'Menthol, Flavonoids', 'Menthol, Menthone', 'Digestive aid, Respiratory relief', 'May cause allergic reactions', 7, 'Throat', 'Air', 'Digestive', 'Respiratory', 9),
('Red Clover', 'https://example.com/red_clover.jpg', 'Flowers', 'Fabaceae', 'Trifolium', 'Isoflavones, Flavonoids', 'Genistein, Daidzein', 'Hormonal balance, Skin health', 'May cause allergic reactions', 6, 'Sacral', 'Water', 'Reproductive', 'Integumentary', 7),
('Sangre de Grado', 'https://example.com/sangre_de_grado.jpg', 'Bark', 'Euphorbiaceae', 'Croton', 'Taspine, Proanthocyanidins', 'Taspine, Proanthocyanidins', 'Wound healing, Anti-inflammatory', 'May cause digestive upset', 6, 'Root', 'Earth', 'Integumentary', 'Immune', 3),
('Sarsaparilla', 'https://example.com/sarsaparilla.jpg', 'Root', 'Smilacaceae', 'Smilax', 'Saponins, Flavonoids', 'Smilax saponin, Flavonoids', 'Detoxification, Hormonal balance', 'May cause digestive upset', 6, 'Root', 'Earth', 'Endocrine', 'Immune', 18),
('Saw Palmetto', 'https://example.com/saw_palmetto.jpg', 'Berries', 'Arecaceae', 'Serenoa', 'Fatty acids, Phytosterols', 'Beta-sitosterol, Lauric acid', 'Prostate health, Hormonal balance', 'May cause digestive upset', 6, 'Root', 'Earth', 'Reproductive', 'Endocrine', 7),
('Schisandra', 'https://example.com/schisandra.jpg', 'Fruit', 'Schisandraceae', 'Schisandra', 'Lignans, Vitamin C', 'Schisandrin, Schisandrol', 'Stress relief, Liver support', 'May cause digestive upset', 7, 'Root', 'Earth', 'Nervous', 'Digestive', 20),
('St. Johns Wort', 'https://example.com/st_johns_wort.jpg', 'Flowers', 'Hypericaceae', 'Hypericum', 'Hypericin, Flavonoids', 'Hypericin, Hyperforin', 'Mood enhancement, Antimicrobial', 'May interact with medications', 7, 'Solar Plexus', 'Fire', 'Nervous', 'Immune', 20),
('Thunder God Vine', 'https://example.com/thunder_god_vine.jpg', 'Root', 'Aristolochiaceae', 'Tripterygium', 'Terpenoids, Lignans, Flavonoids, Saponins', 'Tripterygium Glycosides, Alkaloids', 'Anti-inflammatory, Immunosuppressant', 'May cause gastrointestinal issues, liver toxicity', 7, 'Solar Plexus', 'Fire', 'Immune', 'Musculoskeletal', 19),
('Turmeric', 'https://example.com/turmeric.jpg', 'Rhizome', 'Zingiberaceae', 'Curcuma', 'Curcuminoids, Iron, Manganese', 'Curcumin, Demethoxycurcumin, Bisdemethoxycurcumin', 'Anti-inflammatory, Antioxidant, Pain relief', 'May interact with blood-thinning medications', 8, 'Solar Plexus', 'Fire', 'Immune', 'Musculoskeletal', 13),
('Valerian', 'https://example.com/valerian.jpg', 'Root', 'Valerianaceae', 'Valeriana', 'Valerenic acid, Flavonoids', 'Valerenic acid, Valepotriates', 'Sleep aid, Anxiety relief', 'May cause digestive upset', 7, 'Third Eye', 'Water', 'Nervous', 'Immune', 20),
('White Willow Bark', 'https://example.com/white_willow_bark.jpg', 'Bark', 'Salicaceae', 'Salix', 'Salicin, Flavonoids', 'Salicin, Flavonoids', 'Pain relief, Anti-inflammatory', 'May cause digestive upset', 7, 'Solar Plexus', 'Fire', 'Musculoskeletal', 'Immune', 1),
('Wormwood', 'https://example.com/wormwood.jpg', 'Leaves', 'Asteraceae', 'Artemisia', 'Artemisinin, Flavonoids', 'Artemisinin, Absinthine', 'Digestive aid, Anti-parasitic', 'May cause digestive upset', 6, 'Solar Plexus', 'Fire', 'Digestive', 'Immune', 9),
('Yohimbe', 'https://example.com/yohimbe.jpg', 'Bark', 'Rubiaceae', 'Pausinystalia', 'Yohimbine, Alkaloids', 'Yohimbine', 'Libido enhancement, Weight loss', 'May cause increased heart rate', 7, 'Root', 'Earth', 'Reproductive', 'Endocrine', 7);

INSERT INTO toxins (name, description, imageURL, element, chakra, planet, commonSources, organs, biosystem, addtlsystem, effectsOnAdults, effectsOnChildren, detoxMethods, timeToLeaveBody, biosystem_id) VALUES
('Fluoride', 'A chemical added to water and dental products to prevent tooth decay but harmful in high doses.', 'https://i.pinimg.com/736x/46/08/f3/4608f34a86b8ecfc8111dfa375767b0d.jpg', 'Water', 'Throat', 'Mercury', 'Tap water, Toothpaste, Processed beverages', 'Thyroid, Brain, Pineal Gland', 'Endocrine', 'Neurological', 'May cause thyroid dysfunction and Calcifies the pineal gland.', 'Greater impact on developing brains and bone density.', 'Use fluoride filters and Consume iodine-rich foods.', '6 months to years for stored fluoride in bones.', 18),
('Artificial Food Dyes', 'Synthetic chemicals used to color food and drinks.', 'https://i.pinimg.com/474x/11/63/45/1163458a0d18769f66d508c895c26910.jpg', 'Fire', 'Solar Plexus', 'Sun', 'Candies, Processed snacks, Sodas', 'Brain, Liver', 'Neurological', 'Hepatic', 'May cause hyperactivity, allergic reactions.', 'Linked to behavioral issues and ADHD symptoms.', 'Switch to natural food colorings and Increase water intake.', '1-2 days with cessation of consumption.', 20),
('Lead', 'A toxic heavy metal found in contaminated water, paint, and soil.', 'https://i.pinimg.com/474x/d6/26/ec/d626ec0fe47e04d9d7acf2430de1894f.jpg', 'Earth', 'Root', 'Saturn', 'Old paint, Contaminated water, Batteries', 'Brain, Kidneys, Bones', 'Neurological', 'Renal', 'Cognitive decline, Kidney damage, High blood pressure.', 'Severe developmental delays and Reduced IQ.', 'Chelation therapy plus Calcium and iron-rich foods.', 'Months to years depending on accumulation.', 20),
('Mercury', 'A neurotoxic heavy metal found in seafood and industrial emissions.', 'https://i.pinimg.com/736x/54/c0/73/54c073245cbe5cb2a3abe5f6ce801b77.jpg', 'Water', 'Third Eye', 'Moon', 'Fish (tuna, swordfish), Thermometers, Dental fillings', 'Brain, Kidneys, Immune', 'Neurological', 'Immune', 'Tremors, Memory loss, Immune suppression.', 'Severe effects on brain development and behavior.', 'Chelation therapy and Selenium-rich foods.', 'Months to years depending on exposure levels.', 20),
('Arsenic', 'A toxic metalloid found in contaminated water and rice.', 'https://i.pinimg.com/474x/70/74/d3/7074d36ca6d7d2506c939547a519f9fc.jpg', 'Earth', 'Root', 'Pluto', 'Groundwater, Rice, Pesticides', 'Liver, Lungs, Skin', 'Hepatic, Respiratory, Integumentary', 'Skin lesions, Respiratory irritation, Cancer.', 'Increased risk of cancer and developmental toxicity.', 'Consume sulfur-rich foods and reverse osmosis filtration.', '2-4 days for low-level exposure.'),
('Bisphenol A (BPA)', 'An endocrine disruptor found in plastics.', 'Air', 'Heart', 'Venus', 'Plastic bottles, food cans, receipts', 
 'Endocrine glands, brain', 'Endocrine, neurological', 
 'Hormonal imbalance, infertility.', 
 'Endocrine disruption, early puberty.', 
 'Avoid plastic containers, eat antioxidant-rich foods.', 
 '3-5 days with reduced exposure.'),
('Phthalates', 'Chemicals used to soften plastics and in personal care products.', 'Water', 'Sacral', 'Moon', 'Plastic toys, shampoos, vinyl flooring', 
 'Reproductive organs, liver', 'Endocrine, hepatic', 
 'Infertility, liver dysfunction.', 
 'Hormonal disruption, impacts reproductive development.', 
 'Avoid phthalate-containing products, detox with cruciferous vegetables.', 
 '3-10')
 ('Aluminum', 'A lightweight metal linked to neurological disorders.', 'Air', 'Crown', 'Uranus', 'Deodorants, cookware, vaccines', 
 'Brain, bones', 'Neurological, skeletal', 
 'May contribute to Alzheimer’s disease, bone weakness.', 
 'Impaired brain development and bone growth.', 
 'Increase silica and antioxidant intake.', 
 '1-2 days with minimal exposure; accumulates in tissues over time.'),
 ('Pesticides (Chlorpyrifos)', 'Chemicals used to kill pests but harmful to human health.', 'Earth', 'Root', 'Mars', 'Non-organic produce, agricultural run-off', 
 'Liver, brain, endocrine glands', 'Hepatic, neurological, endocrine', 
 'Hormonal disruption, cancer, neurotoxicity.', 
 'Higher risk of developmental disorders and ADHD.', 
 'Wash produce thoroughly, switch to organic foods.', 
 '1-2 weeks for some; others persist for years.'),-- Radiation (General)
('Radiation', 'Energy from natural and artificial sources harmful in high doses.', 'Fire', 'Third Eye', 'Sun', 'Phones, microwaves, X-rays', 
 'Brain, reproductive organs', 'Neurological, reproductive', 
 'May increase cancer risk, damage DNA.', 
 'Greater damage to developing tissues and organs.', 
 'Limit exposure, use radiation-blocking tools, antioxidant support.', 
 'Depends on exposure; oxidative damage may persist.'),
-- Formaldehyde
('Formaldehyde', 'A carcinogenic substance used in building materials, furniture, and household products, commonly found in tobacco smoke and some cosmetics.', 'Air', 'Heart', 'Mars', 'Building materials, cosmetics, tobacco smoke', 
 'Lungs, skin, liver', 'Respiratory, integumentary, hepatic', 
 'Respiratory issues, skin irritation, liver damage, cancer risk.', 
 'Higher susceptibility in children due to developing immune systems, causing respiratory problems.', 
 'Increase ventilation, avoid products containing formaldehyde, use natural cleaning products.', 
 'Weeks to months, depending on exposure levels.'),
('Sodium Nitrate', 'A preservative in processed meats linked to cancer.', 'Water', 'Root', 'Mars', 'Hot dogs, bacon, processed meats', 
 'Intestines, liver', 'Digestive, hepatic', 
 'Increased cancer risk, high blood pressure.', 
 'Higher susceptibility to DNA damage.', 
 'Avoid processed meats, increase vitamin C intake.', 
 '1-2 days after consumption ends.'),

('MSG (Monosodium Glutamate)', 'A flavor enhancer causing neurological and metabolic issues.', 'Water', 'Sacral', 'Mercury', 'Processed snacks, soups, fast foods', 
 'Brain, pancreas', 'Neurological, digestive', 
 'Headaches, insulin resistance, brain fog.', 
 'More severe effects on developing brains.', 
 'Avoid MSG-containing foods, support detox with antioxidants.', 
 '1-2 days with hydration.'),

('Triclosan', 'An antimicrobial agent found in personal care products.', 'Water', 'Throat', 'Mercury', 'Antibacterial soaps, toothpaste, deodorants', 
 'Thyroid, liver', 'Endocrine, hepatic', 
 'Hormonal imbalance, liver damage.', 
 'Greater hormone disruption in children.', 
 'Switch to natural alternatives, support liver detox.', 
 '1-3 days for low-level exposure.'),

('PBDEs (Polybrominated Diphenyl Ethers)', 'Flame retardants used in furniture and electronics.', 'Fire', 'Root', 'Mars', 'Mattresses, electronics, carpets', 
 'Brain, thyroid', 'Neurological, endocrine', 
 'Memory loss, hormone disruption, cancer.', 
 'Higher risk of cognitive impairment.', 
 'Vacuum with HEPA filter, avoid flame-retardant-treated items.', 
 'Years; highly persistent in body fat.'),
 -- Carbon Monoxide
('Carbon Monoxide', 'A colorless, odorless gas that can be deadly when inhaled in high concentrations.', 'Air', 'Heart', 'Venus', 'Car exhaust, gas heaters, wood stoves', 
 'Lungs, heart, brain', 'Respiratory, cardiovascular, neurological', 
 'Headaches, dizziness, shortness of breath.', 
 'Severe developmental issues, reduced oxygen flow to the brain.', 
 'Increase oxygen intake, avoid exposure, use air purifiers.', 
 '1-2 days with fresh air exposure.'),
-- Chlorine
('Chlorine', 'A toxic element used to disinfect water and in industrial processes.', 'Water', 'Solar Plexus', 'Mars', 'Swimming pools, bleach, industrial chemicals', 
 'Lungs, skin', 'Respiratory, integumentary', 
 'Respiratory irritation, skin rashes, lung damage.', 
 'Increased vulnerability to respiratory infections.', 
 'Ventilate areas, use protective gear, hydrate with antioxidant-rich water.', 
 'Short-term exposure leaves in a few hours; long-term exposure accumulates.'),
-- Cadmium
('Cadmium', 'A toxic heavy metal found in industrial waste, batteries, and cigarette smoke.', 'Earth', 'Root', 'Saturn', 'Batteries, cigarettes, industrial pollution', 
 'Liver, kidneys, lungs', 'Renal, hepatic, respiratory', 
 'Kidney damage, lung cancer, bone demineralization.', 
 'Children are more sensitive to kidney damage and developmental toxicity.', 
 'Chelation therapy, antioxidants, vitamin D supplementation.', 
 'Years; slow to leave the body.'),
-- Toluene
('Toluene', 'A solvent found in paints, paint thinners, and adhesives.', 'Fire', 'Third Eye', 'Mercury', 'Paints, glues, solvents', 
 'Brain, liver, kidneys', 'Neurological, hepatic, renal', 
 'Headaches, dizziness, liver damage.', 
 'Increased neurodevelopmental risks, especially in infants and toddlers.', 
 'Ventilate spaces, use non-toxic alternatives, increase vitamin C intake.', 
 'Hours to days, depending on exposure levels.'),
-- Perfluorooctanoic Acid (PFOA)
('Perfluorooctanoic Acid (PFOA)', 'A persistent chemical found in nonstick cookware and water-repellent fabrics.', 'Water', 'Sacral', 'Venus', 'Non-stick cookware, stain-resistant fabrics', 
 'Liver, kidneys, reproductive organs', 'Endocrine, hepatic, reproductive', 
 'Liver damage, hormone disruption, developmental toxicity.', 
 'Higher risk of developmental defects and hormone-related disorders.', 
 'Switch to stainless steel cookware, reduce exposure to treated fabrics.', 
 'Years; persistent in the environment and the body.'),
-- Glyphosate
('Glyphosate', 'A herbicide widely used in agriculture, suspected of being carcinogenic.', 'Earth', 'Root', 'Saturn', 'Non-organic produce, genetically modified crops', 
 'Liver, kidneys, gastrointestinal system', 'Hepatic, digestive', 
 'Cancer risk, gut microbiome disruption, hormonal imbalance.', 
 'Increased risk of developmental disorders, autism spectrum disorders.', 
 'Wash produce thoroughly, switch to organic foods.', 
 '1-2 weeks, depending on exposure level.'),
-- Polyvinyl Chloride (PVC)
('Polyvinyl Chloride (PVC)', 'A plastic material used in pipes, flooring, and toys that releases harmful chemicals.', 'Air', 'Root', 'Pluto', 'Pipes, flooring, toys', 
 'Liver, lungs', 'Hepatic, respiratory', 
 'Liver damage, respiratory problems, cancer risk.', 
 'Potentially harmful to children’s developing organs and immune system.', 
 'Avoid PVC-containing products, use alternative materials, ventilate spaces.', 
 'Days to weeks; long-term exposure increases accumulation.'),
-- Asbestos
('Asbestos', 'A naturally occurring mineral once used in construction materials, known for its carcinogenic properties.', 'Earth', 'Root', 'Saturn', 'Old buildings, insulation, roofing', 
 'Lungs, pleura', 'Respiratory, cardiovascular', 
 'Lung cancer, mesothelioma, respiratory disorders.', 
 'Increased risk of lung disease and developmental issues with prolonged exposure.', 
 'Avoid exposure, work with a professional to remove asbestos safely.', 
 'Decades for full symptoms to appear.'),
-- Dioxins
('Dioxins', 'Highly toxic compounds produced during industrial processes and waste incineration.', 'Fire', 'Solar Plexus', 'Mars', 'Industrial emissions, waste incineration', 
 'Liver, immune system, endocrine glands', 'Hepatic, immune, endocrine', 
 'Cancer, liver damage, immune suppression.', 
 'Increased risk of developmental and reproductive disorders in children.', 
 'Limit exposure to industrial pollutants, support liver detoxification.', 
 'Years to decades due to bioaccumulation in fatty tissue.'),
-- Benzene
('Benzene', 'A carcinogenic chemical found in tobacco smoke, industrial emissions, and some household products.', 'Air', 'Throat', 'Mercury', 'Cigarette smoke, car exhaust, industrial emissions', 
 'Liver, bone marrow', 'Hepatic, hematological', 
 'Leukemia, anemia, liver disease.', 
 'Children have a higher risk of developing blood-related cancers.', 
 'Avoid exposure, use air purifiers, support with antioxidants.', 
 'Days to weeks for short-term exposure; years for high exposure.'),
-- Formaldehyde
('Formaldehyde', 'A colorless, strong-smelling gas found in building materials and household products.', 'Air', 'Crown', 'Uranus', 'Pressed wood products, paints, cosmetics', 
 'Lungs, skin', 'Respiratory, integumentary', 
 'Respiratory irritation, skin reactions, cancer risk.', 
 'Higher exposure risk for children leading to developmental issues.', 
 'Increase ventilation, use formaldehyde-free products, hydrate with detoxifying water.', 
 'Days to weeks depending on exposure levels.'),

-- Acetone
('Acetone', 'A volatile organic compound used in nail polish removers, cleaning agents, and industrial products.', 'Air', 'Heart', 'Venus', 'Nail polish removers, cleaning agents, paint thinners', 
 'Liver, brain', 'Hepatic, neurological', 
 'Dizziness, headaches, liver damage.', 
 'Greater vulnerability to brain damage and liver dysfunction in children.', 
 'Increase hydration, use non-toxic alternatives.', 
 '1-3 days, depending on exposure level.'),
 -- Polychlorinated Biphenyls (PCBs)
('Polychlorinated Biphenyls (PCBs)', 'Toxic chemicals once used in industrial equipment like transformers and capacitors, now banned in many countries.', 'Air', 'Solar Plexus', 'Mars', 'Old electrical equipment, contaminated fish', 
 'Liver, immune system, skin', 'Hepatic, immune, integumentary', 
 'Liver damage, immune suppression, skin lesions.', 
 'Children are more vulnerable to developmental and immune dysfunction.', 
 'Avoid consumption of contaminated fish, support liver detoxification, increase antioxidants.', 
 'Years, due to bioaccumulation in fatty tissue.'),
-- Vinyl Chloride
('Vinyl Chloride', 'A chemical used in the production of PVC plastics, highly carcinogenic.', 'Earth', 'Root', 'Saturn', 'PVC pipes, flooring, insulation', 
 'Liver, kidneys, brain', 'Hepatic, renal, neurological', 
 'Liver cancer, neurological damage, kidney dysfunction.', 
 'Increased risk of liver cancer and neurological dysfunction in children.', 
 'Use alternative materials, increase hydration and antioxidants, avoid exposure.', 
 'Months to years, depending on exposure levels.'),
-- Xylene
('Xylene', 'A solvent found in paints, varnishes, and adhesives, harmful when inhaled or absorbed through the skin.', 'Air', 'Third Eye', 'Mercury', 'Paints, adhesives, varnishes', 
 'Liver, brain, kidneys', 'Neurological, hepatic, renal', 
 'Headaches, dizziness, liver damage, kidney dysfunction.', 
 'Increased risk of developmental delays and neurotoxicity in children.', 
 'Ventilate areas well, wear protective gear, increase vitamin C intake.', 
 'Hours to days, depending on exposure levels.'),
-- Butylated HydroxyToluene (BHT)
('Butylated HydroxyToluene (BHT)', 'A chemical preservative used in foods, cosmetics, and pharmaceuticals, known to disrupt hormones.', 'Fire', 'Sacral', 'Mars', 'Processed foods, cosmetics, pharmaceuticals', 
 'Liver, kidneys, endocrine system', 'Hepatic, renal, endocrine', 
 'Liver damage, endocrine disruption, hormone imbalance.', 
 'Children are more vulnerable to hormone disruption and developmental issues.', 
 'Switch to natural products, avoid processed foods with BHT, support liver detoxification.', 
 'Days to weeks, depending on exposure.'),
-- DDT (Dichlorodiphenyltrichloroethane)
('DDT', 'An insecticide banned in many countries due to its harmful effects on health, especially reproductive and neurological systems.', 'Earth', 'Root', 'Saturn', 'Pesticide residues on crops, contaminated water', 
 'Liver, brain, reproductive organs', 'Neurological, hepatic, reproductive', 
 'Reproductive disorders, neurological damage, cancer.', 
 'Increased risk of developmental defects, neurological issues in children.', 
 'Avoid pesticide-laden produce, support liver detoxification, consume organic foods.', 
 'Decades, due to bioaccumulation in fatty tissues.'),
-- Tetrahydrocannabinol (THC) (In large amounts or in sensitive individuals)
('Tetrahydrocannabinol (THC)', 'The psychoactive component of marijuana, which can have both beneficial and harmful effects depending on the amount consumed and individual sensitivity.', 'Water', 'Crown', 'Neptune', 'Marijuana, cannabis products', 
 'Brain, lungs, liver', 'Neurological, respiratory, hepatic', 
 'Short-term memory issues, lung damage, liver strain with overuse.', 
 'Potential impact on brain development and mental health in children.', 
 'Use in moderation, avoid excessive consumption, support liver detoxification.', 
 'Hours to days, depending on the amount consumed.'),
 -- Perfluorooctanoic Acid (PFOA)
('Perfluorooctanoic Acid (PFOA)', 'A chemical used in nonstick cookware, water-repellent clothing, and firefighting foam, linked to cancer and hormone disruption.', 'Water', 'Solar Plexus', 'Jupiter', 'Nonstick cookware, stain-resistant fabric, contaminated water', 
 'Liver, kidneys, immune system', 'Hepatic, renal, immune', 
 'Cancer, liver damage, immune dysfunction.', 
 'Pregnant women and children are at higher risk of developmental and immune system disruption.', 
 'Use alternatives to nonstick cookware, avoid stain-resistant fabrics, filter water for PFOA.', 
 'Years, due to bioaccumulation in the body.'),
-- Acrylamide
('Acrylamide', 'A chemical formed in certain foods when cooked at high temperatures, often found in french fries, potato chips, and coffee.', 'Fire', 'Root', 'Mars', 'Fried foods, potato chips, coffee', 
 'Nervous system, liver', 'Neurological, hepatic', 
 'Cancer, neurological damage, liver strain.', 
 'Children are more vulnerable to the toxic effects on brain development and cancer risk.', 
 'Limit consumption of fried foods, choose lower-heat cooking methods, increase antioxidants.', 
 'Days to weeks, depending on consumption levels.'),
-- Dioxins
('Dioxins', 'A group of toxic compounds formed during industrial processes such as waste incineration, bleaching, and pesticide manufacturing, highly carcinogenic.', 'Earth', 'Root', 'Saturn', 'Contaminated food, industrial byproducts', 
 'Liver, skin, immune system', 'Hepatic, integumentary, immune', 
 'Cancer, immune system suppression, skin disorders.', 
 'Higher exposure to children can lead to developmental defects and immune system disruption.', 
 'Avoid contaminated food sources, support liver detoxification, increase antioxidants.', 
 'Years, due to bioaccumulation in fatty tissues.'),
-- Methanol
('Methanol', 'A type of alcohol used in industrial solvents and antifreeze, can be absorbed through inhalation or ingestion, highly toxic.', 'Water', 'Sacral', 'Neptune', 'Paints, adhesives, antifreeze, industrial chemicals', 
 'Liver, nervous system', 'Hepatic, neurological', 
 'Headaches, nausea, liver damage, blindness, death.', 
 'Children are more vulnerable to severe effects, even in small amounts.', 
 'Avoid exposure to methanol-containing products, support liver detoxification, increase hydration.', 
 'Hours to days, depending on exposure levels.')
 ;


-- INSERT INTO nutrients (name, benefits, recommendedDailyMicrograms, recommendedDailyVisual, solubility, is_storedInBody, biopotency, molecularWeight, chemicalStructure, meltingPoint, boilingPoint, is_antioxidant, foodSources, diseaseProtection, biosystem_id) VALUES
-- ('Calcium', 'Musculoskeletal', '1', 'builds strong bones and teeth, essential for muscle contraction and relaxation, blood clotting, nerve transmission, and cell signaling, Plays a role in hormone secretion and enzyme activation. Helps maintain healthy blood pressure.'),
-- ('Phosphorus', 'Musculoskeletal', 'Hematologic', 'helps build and repair bones and teeth, essential for nerve function and muscle contraction. Part of DNA and RNA. Helps convert food into energy. Part of phospholipids, which carry lipids in blood and help shuttle nutrients into and out of cells.'),
-- ('Manganese', 'Musculoskeletal', '1', 'Helps form bones. Helps metabolize amino acids, cholesterol, and carbohydrates.'),
-- ('Flouride', 'Musculoskeletal', 'Encourages strong bone formation. Keeps dental cavities from starting or worsening', 'Harmful to children in excessive amounts.'),
-- ('Phylloquinone', 'Vitamin K', 'Musculoskeletal', 'Hematologic', 'activates proteins and calcium, necessary for the production of clotting factors in the liver, regulates bone metabolism and density'),
-- ('Calciferol', 'Vitamin D', 'Musculoskeletal', 'Immune', 'plays a role in modulating immune responses and reducing inflammation, regulates calcium and phosphorus levels and bone metabolism, essential for bone growth and development'),
-- ('Potassium', 'Musculoskeletal', 'Nervous', 'Balances fluids in the body. Helps maintain steady heartbeat and send nerve impulses. Needed for muscle contractions. A diet rich in potassium seems to lower blood pressure.'),
-- ('Chromium', 'Hematologic', 'Enhances the activity of insulin, helps maintain normal blood glucose levels, and is needed to free energy from glucose'),
-- ('Iron', 'Hematologic', 'Helps hemoglobin in red blood cells and myoglobin in muscle cells ferry oxygen throughout the body. Needed for chemical reactions in the body and for making amino acids, collagen, neurotransmitters, and hormones.'),
-- ('Alpha-Tocopherol', 'Vitamin E', 'Integumentary', '3', 'maintains healthy skin and mucous membranes', 'antioxidant: protects cells from damage caused by free radicals', 'Protects vitamin A and certain lipids from damage.'),
-- ('Sulfur', 'Integumentary', '3', 'Helps form bridges that shape and stabilize some protein structures. Needed for healthy hair, skin, and nails.'),
-- ('Zinc', 'Immune', '11', 'Helps form many enzymes and proteins, creates new cells. aids in cell division. Frees vitamin A from storage in the liver. Needed for immune system, taste, smell, and wound healing. low zinc levels impair the immune system.'),
-- ('Ascorbic Acid', 'Vitamin C', 'Immune', '11', 'essential for proper functioning of immune cells, such as lymphocytes, Antioxidant: destroys free radicals, protecting cells from damage, aids in the absorption of non-haem iron from plant-based foods. Helps make collagen, a connective tissue that knits together wounds and supports blood vessel walls. Helps make the neurotransmitters serotonin and norepinephrine.'),
-- ('Retinoids & Carotene', 'Vitamin A', 'Immune', 'Integumentary', 'helps regulate the immune response and protect against infections, maintains healthy skin and mucous membranes, Vision: essential for the health and function of the retina and cornea'),
-- ('Chloride', 'Digestive', 'Balances fluids in the body. A component of stomach acid, essential to digestion'),
-- ('Sodium', 'Digestive', 'Endocrine', '7', 'helps regulate fluid balance and is used in the formation of hydrochloric acid (stomach acid) for digestion. Helps send nerve impulses. Needed for muscle contractions. Impacts blood pressure.'),
-- ('Iodine', 'Endocrine', '13', 'essential for the production of thyroid hormones, which helps set body temperature and influences nerve and muscle function, reproduction, and growth, necessary for metabolism and physical and mental development.'),
-- ('Selenium', 'Endocrine', 'Nervous', 'Acts as an antioxidant, neutralizing unstable molecules that can damage cells. Helps regulate thyroid hormone activity'),
-- ('Magnesium', 'Nervous', 'Musculoskeletal', 'acts as a cofactor in several enzymatic reactions, including those involved in nerve function and works with calcium in muscle contraction, blood clotting, and regulation of blood pressure. Helps build bones and teeth.'),
-- ('Copper', 'Nervous', '15', 'required for proper growth and development, carbohydrate metabolism, iron absorption, and immune system. red blood cell formation.'),
-- ('Vitamin B12', 'Nervous', '15', 'plays a crucial role in the formation of myelin, the fatty substance that surrounds and protects nerve fibers, Red blood cell formation: necessary for the production of red blood cells, involved in the metabolism of fatty acids and amino acids.'),
-- ('Thiamine', 'Vitamin B1', 'Nervous', 'Immune', 'plays a role in the synthesis of neurotransmitters and the maintenance of healthy nerve function, supports immune function and response, involved in the breakdown of carbohydrates, fats, and proteins for energy production, necessary for the production of red blood cells'),
-- ('Riboflavin', 'Vitamin B2', 'Helps convert food into energy. Needed for healthy skin, hair, muscles, and brain and is critical for nerve function.'),
-- ('Niacin', 'Vitamin B3', 'Helps convert food into energy. Needed for healthy skin, hair, muscles, and brain and is critical for nerve function.'),
-- ('Pantothenic Acid', 'Vitamin B5', 'Helps convert food into energy. Needed for healthy skin, hair, muscles, and brain and is critical for nerve function. Helps make lipids (fats), neurotransmitters, steroid hormones, and hemoglobin.'),
-- ('Pyridoxine', 'Vitamin B6', 'Helps convert tryptophan to niacin and serotonin, a neurotransmitter that plays key roles in sleep, appetite, and moods.'),
-- ('Cobalamin', 'Vitamin B12','Assists in making new cells and breaking down some fatty acids and amino acids. Protects nerve cells and encourages their normal growth Helps make red blood cells and DNA.'),
-- ('Biotin', 'Helps convert food into energy and synthesize glucose. Helps make and break down some fatty acids. Needed for healthy bones and hair.'),
-- ('Choline', 'Nervous', '15', 'Helps make and release the neurotransmitter acetylcholine, which aids in many nerve and brain activities. Plays a role in metabolizing and transporting fats.'),
-- ('Folate', 'Vitamin B9', 'Vital for new cell creationHelps prevent brain and spine birth defects when taken early in pregnancy'),
-- ('Molybdenum', 'Nervous', 'Part of several enzymes, one of which helps ward off a form of severe neurological damage in infants that can lead to early death'),
-- ('Protein', 'Amino Acids', 'Musculoskeletal', 'Necessary for tissue formation, cell reparation, and hormone and enzyme production. essential for building strong muscles and a healthy immune system.'),
-- ('Carbohydrates', 'Provide a ready source of energy for the body and provide structural constituents for the formation of cells.'),
-- ('Fat', 'Provides stored energy for the body, functions as structural components of cells, and signaling molecules for proper cellular communication. It provides insulation to vital organs and works to maintain body temperature.'),
-- ('Phytochemicals', 'Give plants their distinctive colors and characteristic flavors and aromas'),
-- ('Caroenoids', 'α-carotene, xanthophylls, and lycopene: strong antioxidant agents, which can extinct the singlet oxygen and reduce oxidative stress as well as react as effective protector to retard the growth of cancerous cells. lutein and astaxanthin: prevention of sever diseases like cancer, cardiovascular disease and cataracts, and they also perform excellent antioxidant, antimicrobial and anti-inflammatory properties'),
-- ('Water','Transports essential nutrients to all body parts, transports waste products for disposal, and aids with body temperature maintenance.');

-- Cellular Regeneration (protein, zinc, vitamin e, folate, vitamin c)
-- Bones (flouride, calcium, phosphorus, vitamin D, vitamin k, cobalamin-b12)
-- Blood (sodium, iron, chromium, copper, calcium, vitamin k)
-- Skin (sulfur, vitamin e, selenium,)
-- Womb (chloride, vitamin A)
-- Appetite
-- Release 
-- Breath
-- Heart
-- Emotions
-- Relaxation (calcium, sodium, potassium, magnesium)
-- Nerves (sodium, potassium, magnesium)
-- Energy (choline, b-vitamins, iron)
-- Thyroid (iodine, )
-- Protection (fat, zinc, vitamin A, vitamin D, vitamin e, vitamin c, selenium, phytochemicals)
-- Vision (vitamin A)
-- Brain (choline,)
-- Sleep
-- System Rebalancing (blood pressure, hormones, body tempature, alkalinity, endocrine, fat, chromium, sodium, chloride, potassium)

-- atp
-- atg


-- Sources

-- Teeth & Spinal Cord & & Hands & Toes connected to organs