\c herbology_dev;

INSERT INTO herbs (name, imageURL, family, genus, nutrients, partsUsed, activeCompounds, medicinalUses, precautions, potencyRating, is_perennial, biosystem) VALUES
('Turmeric', 'https://example.com/turmeric.jpg', 'Zingiberaceae', 'Curcuma', 'Curcuminoids, Iron, Manganese', 'Rhizome', 'Curcumin, Demethoxycurcumin, Bisdemethoxycurcumin', 'Anti-inflammatory, Antioxidant, Pain relief', 'May interact with blood-thinning medications', 8, true, 'Immune System, Musculoskeletal System'),
('Ginger', 'https://example.com/ginger.jpg', 'Zingiberaceae', 'Zingiber', 'Gingerol, Vitamin B6, Potassium', 'Rhizome', 'Gingerol, Shogaol, Zingerone', 'Anti-nausea, Anti-inflammatory, Pain relief', 'May cause digestive upset in large amounts', 7, true, 'Digestive System, Immune System'),
('Lavender', 'https://example.com/lavender.jpg', 'Lamiaceae', 'Lavandula', 'Linalool, Linalyl acetate, Vitamin A', 'Flowers', 'Linalool, Linalyl acetate, Cineole', 'Anxiety relief, Sleep aid, Antiseptic', 'May cause skin irritation in sensitive individuals', 5, true, 'Nervous System, Skin');

INSERT INTO biosystems (name, description, function, primaryOrgans, associatedDiseases, element, chakra, has_regenerative_capacity, averageRecoveryTime) VALUES
('Musculoskeletal System', 'The system providing structural support, movement, and protection for the body.', 'Supports body structure, enables movement, and protects vital organs.', 'Bones, Muscles, Joints', 'Osteoporosis, Arthritis, Muscular Dystrophy', 'Root', 'Earth', true, 30),
('Hematologic System', 'The system involved in the production and function of blood cells and the blood-forming organs.', 'Responsible for blood production, immune response, and oxygen transport.', 'Bone Marrow, Blood, Spleen', 'Anemia, Leukemia, Hemophilia', 'Fire', 'Root', true, 7), 
('Integumentary System', 'The system that includes the skin and its associated structures.', 'Protects the body from external damage and regulates temperature.', 'Skin, Hair, Nails', 'Eczema, Psoriasis, Acne', 'Root', 'Earth', true, 14),
('Urinary System', 'The system responsible for eliminating waste and regulating fluid and electrolyte balance.', 'Filters blood to produce urine and regulates fluid and electrolyte balance.', 'Kidneys, Ureters, Bladder, Urethra', 'Urinary Tract Infections, Kidney Stones, Incontinence', 'Sacral', 'Water', true, 21),
('Reproductive System', 'The system involved in producing offspring and regulating sexual functions.', 'Facilitates reproduction and regulates sexual health.', 'Ovaries, Uterus, Testes, Prostate', 'Infertility, Polycystic Ovary Syndrome, Erectile Dysfunction', 'Sacral', 'Water', true, 30),
('Excretory System', 'The system responsible for removing waste products and excess substances from the blood.', 'Filters and eliminates waste through various mechanisms.', 'Kidneys, Bladder, Urethra, Skin', 'Kidney Stones, Urinary Tract Infections, Sweat Disorders', 'Water', 'Sacral', true, 14),
('Digestive System', 'A complex system responsible for breaking down food, absorbing nutrients, and expelling waste.', 'Breaks down food into nutrients, absorbs nutrients, and removes waste.', 'Stomach, Intestines, Liver, Pancreas, Gallbladder', 'Gastritis, Peptic Ulcers, Irritable Bowel Syndrome, Crohns Disease', 'Solar Plexus', 'Fire', true, 7),
('Cardiovascular System', 'The system that circulates blood throughout the body, delivering oxygen and nutrients while removing waste.', 'Pumps blood throughout the body, delivering oxygen and nutrients to tissues and removing waste products.', 'Heart, Blood Vessels, Blood', 'Hypertension, Heart Disease, Atherosclerosis', 'Heart', 'Water', true, 10),
('Respiratory System', 'The system responsible for the exchange of oxygen and carbon dioxide between the body and the environment.', 'Facilitates breathing by exchanging gases between the blood and the air.', 'Lungs, Trachea, Bronchi, Diaphragm', 'Asthma, Chronic Obstructive Pulmonary Disease (COPD), Pneumonia', 'Heart', 'Air', false, 14),
('Lymphatic System', 'A network of tissues and organs that help rid the body of toxins and waste.', 'Transports lymph, a fluid containing infection-fighting white blood cells.', 'Lymph Nodes, Lymph Vessels, Spleen, Thymus', 'Lymphedema, Lymphoma, Tonsillitis', 'Water', 'Heart', true, 20),
('Immune System', 'The system that defends the body against infections and disease.', 'Identifies and destroys pathogens, and removes damaged cells.', 'Lymph Nodes, Spleen, Bone Marrow, Antibodies', 'Autoimmune Diseases, Allergies, Immunodeficiency Disorders', 'Throat', 'Ether', true, 14),
('Sensory System', 'The part of the nervous system responsible for processing sensory information.', 'Receives and processes sensory information from the environment.', 'Eyes, Ears, Nose, Tongue, Skin', 'Cataracts, Hearing Loss, Anosmia', 'Ether', 'Third Eye', true, 10),
('Endocrine System', 'A collection of glands that produce hormones regulating metabolism, growth, and other functions.', 'Regulates various physiological processes through hormone secretion.', 'Pituitary Gland, Thyroid Gland, Adrenal Glands', 'Diabetes Mellitus, Hypothyroidism, Addisons Disease', 'Third Eye', 'Air', true, 21),
('Cellular Organelle Systems', 'The systems within cells that carry out specific functions essential for cell survival.', 'Includes mitochondria, nuclei, ribosomes, and endoplasmic reticulum.', 'Mitochondria, Nucleus, Ribosomes, Endoplasmic Reticulum', 'Mitochondrial Diseases, Nucleus Disorders, Ribosomal Protein Deficiencies', 'Ether', 'Crown', true, 5),
('Nervous System', 'The system that transmits nerve impulses between parts of the body and the brain.', 'Controls and coordinates body activities by transmitting electrical signals.', 'Brain, Spinal Cord, Nerves', 'Alzheimers Disease, Parkinsons Disease, Multiple Sclerosis', 'Crown', 'Ether', false, 30);

INSERT INTO nutrients (name, benefits, recommendedDailyMicrograms, recommendedDailyVisual, solubility, is_storedInBody, biopotency, molecularWeight, chemicalStructure, meltingPoint, boilingPoint, is_antioxidant, foodSources, didYouKnow) VALUES
()